import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

const here = fileURLToPath(new URL('.', import.meta.url));
const network = process.env.DFX_NETWORK ?? 'local';
const isDemo = process.env.VITE_DEMO === '1';
// GitHub Pages serves project sites from /<repo>/, so assets need that prefix.
const base = process.env.DEMO_BASE ?? (isDemo ? '/Crowdfunding-ICP/' : '/');

// Canister ids come from dfx's own output rather than a hand-maintained .env,
// so the frontend cannot drift from what is actually deployed.
function canisterIds(): Record<string, string> {
    // Mainnet ids are committed at the repo root; every other network keeps
    // them under .dfx/<network>/, including `playground`.
    const file =
        network === 'ic'
            ? `${here}../canister_ids.json`
            : `${here}../.dfx/${network}/canister_ids.json`;

    if (!existsSync(file)) {
        console.warn(
            `[vite] no canister ids at ${file} — run \`dfx deploy\` first`
        );
        return {};
    }

    const raw: Record<string, Record<string, string>> = JSON.parse(
        readFileSync(file, 'utf8')
    );

    return Object.fromEntries(
        Object.entries(raw)
            .map(([name, nets]) => [name, nets[network] ?? nets.local ?? nets.ic])
            .filter(([, id]) => Boolean(id))
    );
}

export default defineConfig({
    base,
    plugins: [react(), tailwindcss()],
    resolve: {
        alias: {
            // dfx-generated Candid bindings. Regenerated by `dfx deploy`, and
            // gitignored — a fresh clone must build the canister first.
            '@declarations': `${here}../src/declarations`
        }
    },
    define: {
        __CANISTER_IDS__: JSON.stringify(canisterIds()),
        __DFX_NETWORK__: JSON.stringify(network)
    },
    build: {
        outDir: 'dist',
        emptyOutDir: true
    },
    server: {
        // The agent talks to same-origin /api, which dev-proxies to the local
        // replica. In production the asset canister serves both, so the same
        // origin works unchanged.
        proxy: {
            '/api': {
                target: 'http://127.0.0.1:4943',
                changeOrigin: true
            }
        }
    }
});
